### ISSUE TITLE
getComponent reject should return http response back to client

### ISSUE THREAD

**Issue by ryanramage** [airbnb/hypernova#15]
If I return a promise from getComponent, and I decide the name is not valid currently this is the response 

```
 ®[test-hypernova]$ http POST localhost:3030/batch < test/assets/organism.json
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 0
Date: Thu, 16 Jun 2016 20:08:45 GMT
X-Powered-By: Express
``` 
for reference, the posted json looks like: 

```
{
  "test" : {
    "name": "/usr/bin/evil",
    "data": {
      "name": "Ryan"
    }
  }
}
```

a section of my getComponent looks like

```
    getComponent(name) {
      return new Promise((resolve, reject) => {
        // make sure the name has no funny biz
        var parts = name.split('@')
        if (parts.length !== 2) return reject('Weird name passed to us')
        if (!validate(parts[0]).validForNewPackages) return reject('invalid package')
```

Can we make it so the rejected promise makes a 400 status code, and maybe a json response like: 

```
{
    "error": null,
    "results": {
        "test": {
            "duration": 268.287959,
            "error":"invalid package",
            "meta": {},
            "name": "/usr/bin/evil",
            "statusCode": 400,
            "success": false
        }
    },
    "success": false
}
```

**Comment by ljharb** [comment]
This sounds totally reasonable, and could be done before the `.then` in https://github.com/airbnb/hypernova/blob/master/src/utils/BatchManager.js#L139

**Comment by goatslacker** [comment]
If you return a rejected Promise from `getComponent` you'll already trigger an error and `onError` will be [called for all the plugins](https://github.com/airbnb/hypernova/blob/master/src/utils/lifecycle.js#L171-L172).

A response is already returned with the format:

```js
{ name: 'MyComponent',
     html: null,
     meta: {},
     duration: null,
     statusCode: 500,
     success: false,
     error: { name: 'Error', message: 'A rejected promise', stack: [Object] } }
```

so do you just want the `statusCode` to be `400` and `duration` to be not null?

**Comment by ryanramage** [comment]
@goatslacker for some reason I don't get that response back. My response is

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 0
Date: Thu, 16 Jun 2016 20:08:45 GMT
X-Powered-By: Express
```
with an empty body (as suggested by the Content-Length)

I am fine with the message you specified (and statusCode of 500) but I am not seeing that behaviour

**Comment by goatslacker** [comment]
I'll post my setup.

**Comment by goatslacker** [comment]
@ryanramage 

```sh
λ npm ls | grep hypernova
├── hypernova@1.0.0
```

```sh
cat hypernova.js
```

```js
const server = require('hypernova/server')

server({
  devMode: true,
  getComponent() {
    return Promise.reject(new Error('A rejected promise'))
  },
  port: 3030,
})
```

```sh
curl -X POST localhost:3030/batch -H 'Content-Type: application/json' -d '{"foo":{"name":"foo","data":{}}}' | json
```

```json
{
  "success": true,
  "error": null,
  "results": {
    "foo": {
      "name": "foo",
      "html": null,
      "meta": {},
      "duration": null,
      "statusCode": 500,
      "success": false,
      "error": {
        "name": "Error",
        "message": "A rejected promise",
        "stack": [
          "Error: A rejected promise",
          "at getComponent (/tmp/playground/hypernova.js:6:27)",
          "at BatchManager.render (/tmp/playground/node_modules/hypernova/lib/utils/BatchManager.js:163:22)",
          "at /tmp/playground/node_modules/hypernova/lib/utils/lifecycle.js:170:22",
          "at tryCatcher (/tmp/playground/node_modules/hypernova/node_modules/bluebird/js/release/util.js:16:23)",
          "at Promise._settlePromiseFromHandler (/tmp/playground/node_modules/hypernova/node_modules/bluebird/js/release/promise.js:502:31)",
          "at Promise._settlePromise (/tmp/playground/node_modules/hypernova/node_modules/bluebird/js/release/promise.js:559:18)",
          "at Promise._settlePromise0 (/tmp/playground/node_modules/hypernova/node_modules/bluebird/js/release/promise.js:604:10)",
          "at Promise._settlePromises (/tmp/playground/node_modules/hypernova/node_modules/bluebird/js/release/promise.js:683:18)",
          "at Async._drainQueue (/tmp/playground/node_modules/hypernova/node_modules/bluebird/js/release/async.js:138:16)",
          "at Async._drainQueues (/tmp/playground/node_modules/hypernova/node_modules/bluebird/js/release/async.js:148:10)",
          "at Immediate.Async.drainQueues [as _onImmediate] (/tmp/playground/node_modules/hypernova/node_modules/bluebird/js/release/async.js:17:14)",
          "at tryOnImmediate (timers.js:543:15)",
          "at processImmediate [as _immediateCallback] (timers.js:523:5)"
        ]
      }
    }
  }
}
```

**Comment by goatslacker** [comment]
There are reasons why you might be getting an empty response and that's maybe because you're passing an empty request. The request format matters, you can see an example above in my `curl` request. Another thing is that there should be a `Content-Type` header set to `application/json` so that [`body-parser`](https://github.com/expressjs/body-parser) extracts the jobs from the request.

**Comment by ryanramage** [comment]
@goatslacker thanks. that fixed it for me. It was actually one of my rejects was returning a string and not an Error object.

**Comment by goatslacker** [comment]
Looks like a bug. I'll get that fixed.
